replicaCount: 1

image:
  repository: parekhmeet/go-deploy
  pullPolicy: IfNotPresent
  tag: "10101663045"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

